name: Build

on:
  push:
    branches:
      - '*' # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BitCrafts.Core.sln

      - name: Build project
        run: dotnet build BitCrafts.Core.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BitCrafts.Core.sln --no-restore --verbosity normal
