name: Build, Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore BitCrafts.Core.sln

      - name: Build project
        run: dotnet build BitCrafts.Core.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BitCrafts.Core.sln --no-restore --verbosity normal

      - name: Extract tag version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Pack NuGet package BitCrafts.Infrastructure
        run: dotnet pack src/Infrastructure/BitCrafts.Infrastructure/BitCrafts.Infrastructure.csproj --configuration Release --no-restore --output . /p:AssemblyVersion=${{ steps.extract_version.outputs.VERSION }} /p:FileVersion=${{ steps.extract_version.outputs.VERSION }} /p:Version=${{ steps.extract_version.outputs.VERSION }}

      - name: Pack NuGet package BitCrafts.Infrastructure.Abstraction
        run: dotnet pack src/Infrastructure/BitCrafts.Infrastructure.Abstraction/BitCrafts.Infrastructure.Abstraction.csproj --configuration Release --no-restore --output . /p:AssemblyVersion=${{ steps.extract_version.outputs.VERSION }} /p:FileVersion=${{ steps.extract_version.outputs.VERSION }} /p:Version=${{ steps.extract_version.outputs.VERSION }}

      - name: Pack NuGet package BitCrafts.Application.Abstraction
        run: dotnet pack src/Applications/BitCrafts.Application.Abstraction/BitCrafts.Application.Abstraction.csproj --configuration Release --no-restore --output . /p:AssemblyVersion=${{ steps.extract_version.outputs.VERSION }} /p:FileVersion=${{ steps.extract_version.outputs.VERSION }} /p:Version=${{ steps.extract_version.outputs.VERSION }}
        
      - name: Pack NuGet package BitCrafts.Application.Avalonia
        run: dotnet pack src/Applications/BitCrafts.Application.Avalonia/BitCrafts.Application.Avalonia.csproj --configuration Release --no-restore --output . /p:AssemblyVersion=${{ steps.extract_version.outputs.VERSION }} /p:FileVersion=${{ steps.extract_version.outputs.VERSION }} /p:Version=${{ steps.extract_version.outputs.VERSION }}
        
      - name: Pack NuGet package BitCrafts.Application.Avalonia.Controls
        run: dotnet pack src/Applications/BitCrafts.Application.Avalonia.Controls/BitCrafts.Application.Avalonia.Controls.csproj --configuration Release --no-restore --output . /p:AssemblyVersion=${{ steps.extract_version.outputs.VERSION }} /p:FileVersion=${{ steps.extract_version.outputs.VERSION }} /p:Version=${{ steps.extract_version.outputs.VERSION }}
        
      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push *.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --skip-duplicate --no-symbols
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
